name: Shellcheck

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  shellcheck:
    name: Run shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run shellcheck on bash files
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          scandir: '.'
          severity: warning
          ignore_paths: '.git .github .bash_autocompletions'
        env:
          SHELLCHECK_OPTS: -e SC1090 -e SC2148
